-- Generate and insert 50 products
INSERT INTO products (name)
VALUES ('Smartphone X'),
       ('Laptop Pro'),
       ('Wireless Headphones'),
       ('Smartwatch Elite'),
       ('Ultra HD TV'),
       ('Digital Camera Plus'),
       ('Gaming Console 2000'),
       ('Fitness Tracker Slim'),
       ('Noise-Canceling Earbuds'),
       ('Tablet Nova'),
       ('Coffee Maker Deluxe'),
       ('Blender Master'),
       ('Robot Vacuum Cleaner'),
       ('Electric Toothbrush'),
       ('Smart Thermostat'),
       ('Home Security Camera'),
       ('Drone Explorer'),
       ('Portable Bluetooth Speaker'),
       ('E-book Reader Prime'),
       ('3D Printer Pro'),
       ('Electric Scooter Max'),
       ('Virtual Reality Headset'),
       ('Wireless Charging Pad'),
       ('Smart Refrigerator'),
       ('Air Purifier Ultra'),
       ('Outdoor Grill Supreme'),
       ('Smart Home Hub'),
       ('Smart Doorbell Pro'),
       ('Car Dash Cam HD'),
       ('Folding Bike Lite'),
       ('Bluetooth Keyboard'),
       ('High-Performance Router'),
       ('Digital Photo Frame'),
       ('Compact Espresso Machine'),
       ('Wireless Mouse Precision'),
       ('Mini Projector Portable'),
       ('Hybrid Smartwatch'),
       ('Bluetooth Earbuds Sport'),
       ('Fitness Smart Scale'),
       ('Solar-Powered Charger'),
       ('Cordless Hand Vacuum'),
       ('Smart Mirror Touch'),
       ('Multi-Port USB Charger'),
       ('HD Webcam Premium'),
       ('Smart Desk Lamp'),
       ('Ultra-Thin Laptop Bag'),
       ('Smart Water Bottle'),
       ('Desktop Air Circulator'),
       ('Wireless Charging Stand');